apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    meta.helm.sh/release-name: hypers-v1
    meta.helm.sh/release-namespace: hyperswitch
  creationTimestamp: "2024-06-19T05:28:18Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: hyperswitch-server-v1o107o0
  namespace: hyperswitch
  resourceVersion: "78628"
  uid: 892a257f-6264-4fb0-aac5-a6fa2af0c534
spec:
  maxReplicas: 1500
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 50
        type: Utilization
    type: Resource
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hyperswitch-server-v1o107o0
status:
  conditions:
  - lastTransitionTime: "2024-06-19T05:28:33Z"
    message: recommended size matches current size
    reason: ReadyForNewScale
    status: "True"
    type: AbleToScale
  - lastTransitionTime: "2024-06-19T05:29:18Z"
    message: the HPA was able to successfully calculate a replica count from cpu resource
      utilization (percentage of request)
    reason: ValidMetricFound
    status: "True"
    type: ScalingActive
  - lastTransitionTime: "2024-06-19T06:10:02Z"
    message: the desired replica count is less than the minimum replica count
    reason: TooFewReplicas
    status: "True"
    type: ScalingLimited
  currentMetrics:
  - resource:
      current:
        averageUtilization: 1
        averageValue: 2m
      name: cpu
    type: Resource
  currentReplicas: 3
  desiredReplicas: 3
